# The main config file for your Jekyll template

# Site settings
title: The Hiding Hand               # used for the html title of every page
desc: >
  Essays by Stefano Zorzi

url: http://www.thehidinghand.com      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url
title_image: "/assets/img/logoeye.png"

# Meta settings
email: sfnzrz@gmail.com 
author: Stefano Zorzi
twitter_username: stefanozorzi
github_username: stefanozorzi
github_source: jackal

# Put your ga tracking code below
google_analytics: 'UA-43398182-2'

# Pagination settings
paginate: 10                           # number of posts to show per page
paginate_path: "/posts/page:num/"  # link scheme for articles, should be letf as is
## excerpt_separator: <!–break–>

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Home
    url: /index.html
    desc: Home
  - title: All Posts
    url: /posts/
    desc: Posts
  - title: Reading
    url: /reading/
    desc: Stuff I am reading
  - title: About me
    url: /about/
    desc: A few things about me

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true         # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

